apiVersion: v1 # the api Version in which the resource is present.
kind: Pod
metadata:
  name: my-pod-conf-map
  labels:
    storageType: config-map
    env: dev
spec:
  volumes:
  - name: config-map-vol
    configMap:
      name: my-config-map
      items:
      - key: httpd.conf # the file name from which config-map is created
        path: raghav.conf
        # the path where to mount this file in the container.
  containers:
  - name: my-pod-config-map
    image: httpd
    volumeMounts: # exactly equal to mount device mountPath
    - name: config-map-vol
      mountPath: /root/
